# Generated by Django 2.1.dev20180312174936 on 2019-03-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jon',
            new_name='Job',
        ),
    ]
